# ---------------------------------------------------------------------------- #
#                      Config for NL2CAD Model Inference/Testing               #
# ---------------------------------------------------------------------------- #

# ---------------------- Configuration for text encoder ---------------------- #
text_encoder:
  # ----------------- Configuration for the Base Text Embedder ----------------- #
  text_embedder:
    # Name of the text encoder model
    model_name: "bert_large_uncased"
    # Maximum Text Sequence Length
    max_seq_len: 512
    # Cache Directory
    cache_dir: "c:/Users/86185/Desktop/NL2CAD/cache"

  # ----------------- Configuration for the Adaptive Layer ----------------- #
  adaptive_layer:
    # Input dimension of the text encoder (1024 for bert, else 4096)
    in_dim: 1024 
    # Output dimension of the text encoder (1024 for bert, else 4096)
    out_dim: 1024
    # Number of attention heads in the text encoder
    num_heads: 8
    # Dropout probability in the text encoder
    dropout: 0.1

# ----------------------- Configuration for CAD Decoder ---------------------- #
cad_decoder:
  # Dimension of the latent variable z in the CAD decoder (1024 for bert, else 4096)
  tdim: 1024
  # Dimension of the state variable s in the CAD decoder
  cdim: 256
  # Number of transformer layers in the CAD decoder
  num_layers: 8
  # Number of attention heads in each layer of the CAD decoder
  num_heads: 8
  # Dropout probability in the CAD decoder
  dropout: 0.1
  # Starting level for channel attention in the CAD decoder
  ca_level_start: 2

# --------------- Configuration related to test dataloader --------------- #
test_data:
  # Root directory of the test data
  cad_seq_dir: "G:/text2cad-data/cad_seq/cad_seq"
  # Path to the CSV file containing the text prompts  
  prompt_path: "G:/text2cad-data/validation_data.pkl"
  # JSON file containing information about train, test, and validation splits
  split_filepath: "G:/text2cad-data/train_val_test_split.json"
  # Maximum sequence length for input data
  max_seq_len: 512

# --------------------- Configuration related to testing -------------------- #
test:
  # Batch size for testing
  batch_size: 1
  # Number of workers for the DataLoader during testing
  num_workers: 4
  # Prefetch factor for the DataLoader during testing
  prefetch_factor: 2
  # Directory for logging test information
  log_dir: "C:/Users/86185/Desktop/NL2CAD/repot"
  # Path to saved model checkpoint for testing
  checkpoint_path:  # Will be set by the evaluation script
  # Sampling type: "max" for greedy decoding, "topk" for top-k sampling
  sampling_type: "max"

# ------------------------------ Debug mode flag ----------------------------- #
debug: False

# --------------- Additional information --------------- #
info: "NL2CAD Inference Configuration"
